### PR TITLE
Add Spanish localization

### PR DESCRIPTION
**Pull request by xoascf**

### CODE REVIEW

**Comment by minusium** [comment]
Hey, Thanks for your help but it's not ready for translation yet. A lot of strings should be moved to resources file.

**Comment by xoascf** [comment]
> Hey, Thanks for your help but it's not ready for translation yet. A lot of strings should be moved to resources file.

No problem, this is a draft, so when it's ready, I'll continue.

**Comment by minusium** [comment]
Should I add a language switcher too?

**Comment by xoascf** [comment]
> Should I add a language switcher too?

That would be great, as some may want to change the language without changing the system language.

**Comment by xoascf** [comment]
> Seems like localization doesn't work. You see app in Spanish when you change your system language? I tried to get a list of languages from ResourceContext object and it only returned English.
> 
> EDIT: I just read its document, `Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Languages` only returns languages for current context.

Yes, I see the translation when Windows is set to Spanish, otherwise not.

Oh, I thought it was already possible to change the language at runtime, you see, for WPF I use XAML dictionaries where I can translate and set keys for each localized string, maybe something similar could be implemented for UWP.

Take either of these translation loading methods as an example: 
* [Hardcoded (translations are inside the app, English is the default language)](https://github.com/BlackTasty/Osmo/commit/48738db76c30e8870035931d533f57d6a3f11cab)
* [Dynamic (loads from folder, and sets the system language as default)](https://github.com/dremin/RetroBar/pull/72/files)

If that's not possible, then I guess we can leave it as is.

**Comment by dongle-the-gadget** [comment]
@xoascf There's an API to set the application language on launch (haven't tried this on XAML Islands, but it works in UWP): `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride`

**Comment by minusium** [comment]
I know about `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride` but it requires package identity. MFE is an unpackaged xaml island app (despite we are working on adding support to running as packaged, still we should be able to run unpackaged too)

**Comment by dongle-the-gadget** [comment]
ah

**Comment by minusium** [comment]
> Take either of these translation loading methods as an example

Thanks for your help

**Comment by xoascf** [comment]
> @xoascf There's an API to set the application language on launch (haven't tried this on XAML Islands, but it works in UWP): `Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride`

Hmm, the user must restart the app every time he or she wants to change the language... I don't really like that, I've seen other UWP apps that do exactly the same thing...

**Comment by minusium** [comment]
I added language switcher. Add new strings then I'll merge.

**Comment by minusium** [comment]
> There is a small typo, "Español" should be written as "español"

That's not my fault, that name comes from Windows.

**Comment by minusium** [comment]
Thank you for contributing.

**Pull request merged**
