### PR TITLE
Some changes in Settings window

### PR DESCRIPTION
**Pull request by dongle-the-gadget**
- Use a simpler way of removing the icon and title from the Settings window (documented `UXTheme` API)
- Capitalize the "H" in GitHub 😏
- Add minimize button in window (feel free to remove though)
- Modify rule service to ignore windows made by the program itself.

### CODE REVIEW

**Comment by minusium** [comment]
Cool That's awesome!
I read https://docs.microsoft.com/en-us/windows/win32/dwm/customframe and all I did was documented too, but I didn't know there's a simpler API for that.

**Review by minusium — COMMENTED** [review]
I would add a rule in config file instead, like this:
```
Process: "MicaForEveryone" {
...
}
```

**Comment by dongle-the-gadget** [comment]
> I would add a rule in config file instead, like this:
> 
> ```
> Process: "MicaForEveryone" {
> ...
> }
> ```

You can't be sure that the user will keep the file name `MicaForEveryone.exe` though.

**Comment by minusium** [comment]
> You can't be sure that the user will keep the file name MicaForEveryone.exe though.
why would they change it?👀😂

**Comment by dongle-the-gadget** [comment]
> > You can't be sure that the user will keep the file name MicaForEveryone.exe though.
> 
> why would they change it?👀😂

Well why not?

**Comment by minusium** [comment]
> Well why not?

btw I'm not sure if app applies rules to itself or not, seems like it doesn't. But I think there was a better way without need to modify TargetWindow.

**Comment by dongle-the-gadget** [comment]
> btw I'm not sure if app applies rules to itself or not, seems like it doesn't. But I think there was a better way without need to modify TargetWindow.

The Global rule does apply to itself. I tried.

**Comment by minusium** [comment]
I don't see it applying to MFE in debug logs. Idk why it doesn't do it on my machine.

**Pull request merged**
